FROM node:16
#alpine даёт ошибку

#TODO попробовать https://ru.vuejs.org/v2/cookbook/dockerize-vuejs-app.html

WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH

COPY package.json /frontend/

# RUN npm install
RUN npm install -g npm@latest
RUN npm cache clean --force
RUN npm rm -rf node_modules && rm package-lock.json
RUN npm install

COPY . /frontend

EXPOSE 8080

# CMD npm run serve